version: '3.8'

services:
  # Asset Management Application
  asset-management:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=asset_user
      - DB_PASSWORD=asset_password
      - DB_NAME=asset_management
      - SESSION_SECRET=your-super-secret-session-key-change-in-production
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - asset-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: asset_management
      MYSQL_USER: asset_user
      MYSQL_PASSWORD: asset_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docker-init.sql:/docker-entrypoint-initdb.d/02-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - asset-network

volumes:
  mysql_data:

networks:
  asset-network:
    driver: bridge
