  version: '3.8'

  services:
    mysql:
      image: mysql:8.0
      container_name: asset-db
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: asset_management
        MYSQL_USER: appuser
        MYSQL_PASSWORD: appsecret
      volumes:
        - ./../database.sql:/docker-entrypoint-initdb.d/01-schema.sql
        - ./docker-init.sql:/docker-entrypoint-initdb.d/02-init.sql
        - db-data:/var/lib/mysql
      ports:
        - "3307:3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5

    app:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      container_name: asset-app
      restart: unless-stopped
      ports:
        - "8080:8080"
      environment:
        NODE_ENV: development
        DB_HOST: mysql
        DB_USER: appuser
        DB_PASSWORD: appsecret
        DB_NAME: asset_management
        SESSION_SECRET: secretkey
      depends_on:
        mysql:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "node", "docker/healthcheck.js"]
        interval: 10s
        timeout: 3s
        retries: 3
      volumes:
        - ..:/app

  volumes:
    db-data:
